# Generated by Django 4.2 on 2024-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II'), ('amaro', 'Amaro'), ('mayfair', 'Mayfair'), ('sierra', 'Sierra'), ('willow', 'Willow'), ('hefe', 'HeFe'), ('clarendon', 'Clarendon'), ('gingham', 'Gingham'), ('moon', 'Moon'), ('lark', 'Lark'), ('reyes', 'Reyes'), ('juno', 'Juno'), ('slumber', 'Slumber'), ('crema', 'Crema'), ('ludwig', 'Ludwig'), ('aden', 'Aden'), ('perpetua', 'Perpetua'), ('grayscale', 'Grayscale'), ('sepia', 'Sepia'), ('blur', 'Blur'), ('brightness', 'Brightness'), ('contrast', 'Contrast'), ('hue-rotate', 'Hue-Rotate'), ('invert', 'Invert'), ('saturate', 'Saturate'), ('vintage', 'Vintage'), ('cool', 'Cool'), ('warm', 'Warm')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_saobzq.jpg', upload_to='images/'),
        ),
    ]
