# Generated by Django 4.2 on 2024-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../default_profile_egbrlo.jpg', upload_to='profile_images'),
        ),
    ]
