# Generated by Django 4.2 on 2024-06-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../default_profile_tpcl4s.jpg', upload_to='profile_images'),
        ),
    ]
