# Generated by Django 4.2 on 2024-05-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='post',
        ),
    ]
